export const initialEmployeeState = {
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  firstName: '',
  lastName: '',
  position: '',
  department: '',
  contactNumber: '',
  address: '',
  email: '',
};

export const sampleEmployees = [
  {
    id: 'EMP-0001',
    createdBy: 'Admin',
    createdDate: '2026-01-05',
    updatedBy: 'Admin',
    updatedDate: '2026-01-06',
    code: 'EMP-JDOE-01',
    firstName: 'John',
    lastName: 'Doe',
    position: 'Warehouse Manager',
    department: 'Operations',
    contactNumber: '09171230001',
    address: '12 Example St, Manila',
    email: 'john.doe@example.com',
  },
  {
    id: 'EMP-0002',
    createdBy: 'Admin',
    createdDate: '2026-01-10',
    updatedBy: 'Admin',
    updatedDate: '2026-01-11',
    code: 'EMP-JSMITH-01',
    firstName: 'Jane',
    lastName: 'Smith',
    position: 'Procurement Officer',
    department: 'Purchasing',
    contactNumber: '09171230002',
    address: '34 Sample Ave, QC',
    email: 'jane.smith@example.com',
  },
  {
    id: 'EMP-0003',
    createdBy: 'Admin',
    createdDate: '2026-02-02',
    updatedBy: 'Admin',
    updatedDate: '2026-02-03',
    code: 'EMP-ABROWN-01',
    firstName: 'Alan',
    lastName: 'Brown',
    position: 'Accountant',
    department: 'Finance',
    contactNumber: '09171230003',
    address: '78 Demo Blvd, Makati',
    email: 'alan.brown@example.com',
  },
];
