export const initialProposalFormState = {
  inquiryId: '',
  proposalNumber: '',
  proposalTotal: '',
  location: '',
  projectName: '',
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  customerName: '',
  customerId: '',
  contactNumber: '',
  address: '',
  companyName: '',
  email: '',
  materials: [],
  status: '',
};

export const sampleProposals = [
  {
    inquiryId: 'INQ-0001',
    proposalNumber: 'PRP-0001',
    proposalTotal: '150000',
    location: 'Makati City',
    projectName: 'Office Fit-out',
    id: 'PROP-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PRP-FIT-01',
    name: 'Main Proposal',
    customerName: 'ACME Corp',
    customerId: 'CUST-0001',
    contactNumber: '09171234567',
    address: '123 Ayala Ave, Makati',
    companyName: 'ACME Corporation',
    email: 'procurement@acme.com',
    status: 'Draft',
  },
  {
    inquiryId: 'INQ-0002',
    proposalNumber: 'PRP-0002',
    proposalTotal: '275000',
    location: 'Quezon City',
    projectName: 'Retail Fit-out',
    id: 'PROP-0002',
    createdBy: 'Luis Dela Cruz',
    createdDate: '2026-02-10',
    updatedBy: 'Luis Dela Cruz',
    updatedDate: '2026-02-12',
    code: 'PRP-RET-02',
    name: 'Retail Proposal',
    customerName: 'Beta Retailers',
    customerId: 'CUST-0002',
    contactNumber: '09181234567',
    address: '45 Timog Ave, QC',
    companyName: 'Beta Retailers Inc',
    email: 'sales@beta.com',
    status: 'Approved',
  },
  {
    inquiryId: 'INQ-0003',
    proposalNumber: 'PRP-0003',
    proposalTotal: '98000',
    location: 'Pasig City',
    projectName: 'Small Office Renovation',
    id: 'PROP-0003',
    createdBy: 'Maria Lopez',
    createdDate: '2026-02-20',
    updatedBy: 'Maria Lopez',
    updatedDate: '2026-02-21',
    code: 'PRP-REN-03',
    name: 'Renovation Proposal',
    customerName: 'Gamma Solutions',
    customerId: 'CUST-0003',
    contactNumber: '09191234567',
    address: '88 Ortigas Ave, Pasig',
    companyName: 'Gamma Solutions Co',
    email: 'office@gamma.com',
    status: 'forApproval',
  },
];

export const initialProposalScopeFormState = {
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  proposalId: '',
  forecastedStartDate: '',
  forecastedEndDate: '',
  actualStartDate: '',
  actualEndDate: '',
  scopeOfWork: '',
  percentage: '',
};

export const sampleProposalScopes = [
  {
    id: 'PS-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PS-ELEC-01',
    name: 'Electrical Scope',
    proposalId: 'PROP-0001',
    forecastedStartDate: '2026-03-01',
    forecastedEndDate: '2026-03-20',
    actualStartDate: '2026-03-03',
    actualEndDate: '2026-03-22',
    scopeOfWork: 'Electrical wirings and devices installation',
    percentage: '45',
  },
  {
    id: 'PS-0002',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PS-TOOL-01',
    name: 'Tools and Equipment Scope',
    proposalId: 'PROP-0001',
    forecastedStartDate: '2026-03-05',
    forecastedEndDate: '2026-03-25',
    actualStartDate: '2026-03-06',
    actualEndDate: '2026-03-26',
    scopeOfWork: 'Tools and equipment mobilization',
    percentage: '25',
  },
];
import { sampleMaterialInventory } from '../MaterialInventory/materialInventoryData';

// Derive proposal materials from material inventory for sample data.
export const sampleProposalMaterials = (sampleMaterialInventory || []).map((mi, idx) => {
  const quantity = mi.quantity || '1';
  const unitCost = mi.unitCost || '0';
  const total = (Number(unitCost) * Number(quantity)) || 0;
  const proposalScopeId = idx === 0 ? 'PS-0001' : 'PS-0002';
  return {
    proposalScopeId,
    remarks: mi.name || '',
    assemblyUOM: mi.uom || '',
    assemblyId: mi.id || '',
    assemblyName: mi.name || '',
    extendedCost: String(total),
    materialId: mi.code || mi.id || `MAT-${idx + 1}`,
    materialType: mi.materialType || 'material',
    uom: mi.uom || '',
    unitCost: String(unitCost),
    quantity: String(quantity),
    vat: mi.vat || '',
    wt: mi.wt || '',
    totalCost: String(total),
    margin: '',
    scopeOfWork: '',
    id: `PM-000${idx + 1}`,
    createdBy: mi.createdBy || '',
    createdDate: mi.createdDate || '',
    updatedBy: mi.updatedBy || '',
    updatedDate: mi.updatedDate || '',
    code: mi.code ? `PM-${mi.code}` : `PM-${idx + 1}`,
    name: mi.name || '',
  };
});
