export const initialProposalFormState = {
  inquiryId: '',
  proposalNumber: '',
  proposalTotal: '',
  location: '',
  projectName: '',
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  customerName: '',
  contactNumber: '',
  address: '',
  companyName: '',
  email: '',
};

export const sampleProposals = [
  {
    inquiryId: 'INQ-0001',
    proposalNumber: 'PRP-0001',
    proposalTotal: '150000',
    location: 'Makati City',
    projectName: 'Office Fit-out',
    id: 'PROP-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PRP-FIT-01',
    name: 'Main Proposal',
    customerName: 'ACME Corp',
    contactNumber: '09171234567',
    address: '123 Ayala Ave, Makati',
    companyName: 'ACME Corporation',
    email: 'procurement@acme.com',
  },
];

export const initialProposalScopeFormState = {
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  proposalId: '',
  forecastedStartDate: '',
  forecastedEndDate: '',
  actualStartDate: '',
  actualEndDate: '',
  scopeOfWork: '',
  percentage: '',
};

export const sampleProposalScopes = [
  {
    id: 'PS-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PS-ELEC-01',
    name: 'Electrical Scope',
    proposalId: 'PROP-0001',
    forecastedStartDate: '2026-03-01',
    forecastedEndDate: '2026-03-20',
    actualStartDate: '2026-03-03',
    actualEndDate: '2026-03-22',
    scopeOfWork: 'Electrical wirings and devices installation',
    percentage: '45',
  },
  {
    id: 'PS-0002',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PS-TOOL-01',
    name: 'Tools and Equipment Scope',
    proposalId: 'PROP-0001',
    forecastedStartDate: '2026-03-05',
    forecastedEndDate: '2026-03-25',
    actualStartDate: '2026-03-06',
    actualEndDate: '2026-03-26',
    scopeOfWork: 'Tools and equipment mobilization',
    percentage: '25',
  },
];

export const sampleProposalMaterials = [
  {
    proposalScopeId: 'PS-0001',
    remarks: 'Main electrical materials package',
    assemblyUOM: 'set',
    assemblyId: 'ASM-1001',
    assemblyName: 'Electrical Assembly',
    extendedCost: '45000',
    materialId: 'MAT-2001',
    materialType: 'material',
    uom: 'pcs',
    unitCost: '500',
    quantity: '90',
    vat: '12%',
    wt: '2%',
    totalCost: '50400',
    margin: '15%',
    scopeOfWork: 'Electrical wirings and devices installation',
    id: 'PM-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PM-ELEC-01',
    name: 'Electrical Package',
  },
  {
    proposalScopeId: 'PS-0002',
    remarks: 'Site tools allocation',
    assemblyUOM: 'set',
    assemblyId: 'ASM-1002',
    assemblyName: 'Tools Assembly',
    extendedCost: '12000',
    materialId: 'TOL-3001',
    materialType: 'tool',
    uom: 'unit',
    unitCost: '3000',
    quantity: '4',
    vat: '12%',
    wt: '2%',
    totalCost: '13440',
    margin: '10%',
    scopeOfWork: 'Tools for installation and finishing',
    id: 'PM-0002',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PM-TOOL-01',
    name: 'Tools Package',
  },
];
