export const initialProposalFormState = {
  inquiryId: '',
  proposalNumber: '',
  proposalTotal: '',
  location: '',
  projectName: '',
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  customerName: '',
  customerId: '',
  contactNumber: '',
  address: '',
  companyName: '',
  email: '',
  materials: [],
  status: '',
};

export const sampleProposals = [
  {
    inquiryId: 'INQ-0001',
    proposalNumber: 'PRP-0001',
    proposalTotal: '150000',
    location: 'Makati City',
    projectName: 'Office Fit-out',
    id: 'PROP-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PRP-FIT-01',
    name: 'Main Proposal',
    customerName: 'ACME Corp',
    customerId: 'CUST-0001',
    contactNumber: '09171234567',
    address: '123 Ayala Ave, Makati',
    companyName: 'ACME Corporation',
    email: 'procurement@acme.com',
    status: 'Draft',
  },
  {
    inquiryId: 'INQ-0002',
    proposalNumber: 'PRP-0002',
    proposalTotal: '275000',
    location: 'Quezon City',
    projectName: 'Retail Fit-out',
    id: 'PROP-0002',
    createdBy: 'Luis Dela Cruz',
    createdDate: '2026-02-10',
    updatedBy: 'Luis Dela Cruz',
    updatedDate: '2026-02-12',
    code: 'PRP-RET-02',
    name: 'Retail Proposal',
    customerName: 'Beta Retailers',
    customerId: 'CUST-0002',
    contactNumber: '09181234567',
    address: '45 Timog Ave, QC',
    companyName: 'Beta Retailers Inc',
    email: 'sales@beta.com',
    status: 'Approved',
  },
  {
    inquiryId: 'INQ-0003',
    proposalNumber: 'PRP-0003',
    proposalTotal: '98000',
    location: 'Pasig City',
    projectName: 'Small Office Renovation',
    id: 'PROP-0003',
    createdBy: 'Maria Lopez',
    createdDate: '2026-02-20',
    updatedBy: 'Maria Lopez',
    updatedDate: '2026-02-21',
    code: 'PRP-REN-03',
    name: 'Renovation Proposal',
    customerName: 'Gamma Solutions',
    customerId: 'CUST-0003',
    contactNumber: '09191234567',
    address: '88 Ortigas Ave, Pasig',
    companyName: 'Gamma Solutions Co',
    email: 'office@gamma.com',
    status: 'forApproval',
  },
];

export const initialProposalScopeFormState = {
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  proposalId: '',
  forecastedStartDate: '',
  forecastedEndDate: '',
  actualStartDate: '',
  actualEndDate: '',
  scopeOfWork: '',
  percentage: '',
};

export const sampleProposalScopes = [
  {
    id: 'PS-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PS-ELEC-01',
    name: 'Electrical Scope',
    proposalId: 'PROP-0001',
    forecastedStartDate: '2026-03-01',
    forecastedEndDate: '2026-03-20',
    actualStartDate: '2026-03-03',
    actualEndDate: '2026-03-22',
    scopeOfWork: 'Electrical wirings and devices installation',
    percentage: '45',
  },
  {
    id: 'PS-0002',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'PS-TOOL-01',
    name: 'Tools and Equipment Scope',
    proposalId: 'PROP-0001',
    forecastedStartDate: '2026-03-05',
    forecastedEndDate: '2026-03-25',
    actualStartDate: '2026-03-06',
    actualEndDate: '2026-03-26',
    scopeOfWork: 'Tools and equipment mobilization',
    percentage: '25',
  },
  {
    id: 'PS-0003',
    createdBy: 'Luis Dela Cruz',
    createdDate: '2026-02-10',
    updatedBy: 'Luis Dela Cruz',
    updatedDate: '2026-02-12',
    code: 'PS-RETL-01',
    name: 'Retail Fit-out Scope',
    proposalId: 'PROP-0002',
    forecastedStartDate: '2026-03-10',
    forecastedEndDate: '2026-04-05',
    actualStartDate: '',
    actualEndDate: '',
    scopeOfWork: 'Retail display fixtures and lighting',
    percentage: '60',
  },
  {
    id: 'PS-0004',
    createdBy: 'Maria Lopez',
    createdDate: '2026-02-20',
    updatedBy: 'Maria Lopez',
    updatedDate: '2026-02-21',
    code: 'PS-REN-01',
    name: 'Renovation Scope',
    proposalId: 'PROP-0003',
    forecastedStartDate: '2026-04-01',
    forecastedEndDate: '2026-04-20',
    actualStartDate: '',
    actualEndDate: '',
    scopeOfWork: 'Small office demolition and refinish',
    percentage: '30',
  },
];
import { sampleMaterialInventory } from '../MaterialInventory/materialInventoryData';

// Derive proposal materials from material inventory for sample data.
const _baseProposalMaterials = (sampleMaterialInventory || []).map((mi, idx) => {
  const quantity = mi.quantity || '1';
  const unitCost = mi.unitCost || '0';
  const total = (Number(unitCost) * Number(quantity)) || 0;
  // distribute materials across available scopes so each proposal has materials
  const scopeIds = ['PS-0001', 'PS-0002', 'PS-0003', 'PS-0004'];
  const proposalScopeId = scopeIds[idx % scopeIds.length];
  return {
    proposalScopeId,
    remarks: mi.name || '',
    assemblyUOM: mi.uom || '',
    assemblyId: mi.id || '',
    assemblyName: mi.name || '',
    extendedCost: String(total),
    materialId: mi.code || mi.id || `MAT-${idx + 1}`,
    materialType: mi.materialType || 'material',
    uom: mi.uom || '',
    unitCost: String(unitCost),
    quantity: String(quantity),
    vat: mi.vat || '',
    wt: mi.wt || '',
    totalCost: String(total),
    margin: '',
    scopeOfWork: '',
    id: `PM-000${idx + 1}`,
    createdBy: mi.createdBy || '',
    createdDate: mi.createdDate || '',
    updatedBy: mi.updatedBy || '',
    updatedDate: mi.updatedDate || '',
    code: mi.code ? `PM-${mi.code}` : `PM-${idx + 1}`,
    name: mi.name || '',
  };
});

// Ensure each scope has at least one sample material. Add explicit materials for PS-0003 and PS-0004
const extraMaterials = [
  {
    proposalScopeId: 'PS-0003',
    remarks: 'Retail display LED strip',
    assemblyUOM: 'pcs',
    assemblyId: 'MI-0003',
    assemblyName: 'LED Strip Light',
    extendedCost: '12000',
    materialId: 'MAT-LED-003',
    materialType: 'material',
    uom: 'm',
    unitCost: '1200',
    quantity: '10',
    vat: '12%',
    wt: '2%',
    totalCost: '12000',
    margin: '',
    scopeOfWork: '',
    id: 'PM-0003',
    createdBy: 'Luis Dela Cruz',
    createdDate: '2026-02-11',
    updatedBy: 'Luis Dela Cruz',
    updatedDate: '2026-02-12',
    code: 'PM-MAT-LED-003',
    name: 'LED Strip Light',
  },
  {
    proposalScopeId: 'PS-0004',
    remarks: 'Flooring tiles',
    assemblyUOM: 'sqm',
    assemblyId: 'MI-0004',
    assemblyName: 'Porcelain Tile',
    extendedCost: '50000',
    materialId: 'MAT-TIL-004',
    materialType: 'material',
    uom: 'sqm',
    unitCost: '500',
    quantity: '100',
    vat: '12%',
    wt: '2%',
    totalCost: '50000',
    margin: '',
    scopeOfWork: '',
    id: 'PM-0004',
    createdBy: 'Maria Lopez',
    createdDate: '2026-02-21',
    updatedBy: 'Maria Lopez',
    updatedDate: '2026-02-21',
    code: 'PM-MAT-TIL-004',
    name: 'Porcelain Tile',
  },
];

export const sampleProposalMaterials = [ ..._baseProposalMaterials, ...extraMaterials ];
