export const initialCustomerState = {
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  customerName: '',
  contactNumber: '',
  address: '',
  companyName: '',
  email: '',
};

export const sampleCustomers = [
  {
    id: 'CUST-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-15',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-16',
    code: 'CST-ACME-01',
    name: 'Primary Account',
    customerName: 'ACME Corp',
    contactNumber: '09171234567',
    address: '123 Ayala Ave, Makati',
    companyName: 'ACME Corporation',
    email: 'procurement@acme.com',
  },
  {
    id: 'CUST-0002',
    createdBy: 'Luis Dela Cruz',
    createdDate: '2026-02-10',
    updatedBy: 'Luis Dela Cruz',
    updatedDate: '2026-02-12',
    code: 'CST-BETA-01',
    name: 'Retail Account',
    customerName: 'Beta Retailers',
    contactNumber: '09181234567',
    address: '45 Timog Ave, QC',
    companyName: 'Beta Retailers Inc',
    email: 'sales@beta.com',
  },
  {
    id: 'CUST-0003',
    createdBy: 'Maria Lopez',
    createdDate: '2026-02-20',
    updatedBy: 'Maria Lopez',
    updatedDate: '2026-02-21',
    code: 'CST-GAM-01',
    name: 'Solutions Account',
    customerName: 'Gamma Solutions',
    contactNumber: '09191234567',
    address: '88 Ortigas Ave, Pasig',
    companyName: 'Gamma Solutions Co',
    email: 'office@gamma.com',
  },
];
