export const initialMaterialInventoryState = {
  materialType: '',
  uom: '',
  unitCost: '',
  quantity: '',
  vat: '',
  wt: '',
  totalCost: '',
  id: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
};

export const sampleMaterialInventory = [
  {
    materialType: 'material',
    uom: 'pcs',
    unitCost: '500',
    quantity: '120',
    vat: '12%',
    wt: '2%',
    totalCost: '67200',
    id: 'MI-0001',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-20',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-22',
    code: 'MAT-EL-001',
    name: 'Electrical Wire Roll',
  },
  {
    materialType: 'tool',
    uom: 'unit',
    unitCost: '4500',
    quantity: '8',
    vat: '12%',
    wt: '2%',
    totalCost: '40320',
    id: 'MI-0002',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-20',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-23',
    code: 'TOL-DRL-002',
    name: 'Heavy Duty Drill',
  },
];
