export const initialInquiryFormState = {
  id: '',
  requestedBy: '',
  requestDate: '',
  approvalStatus: 'Pending',
  responseBy: '',
  responseDate: '',
  attention: '',
  preparedBy: '',
  notedBy: '',
  reference: '',
  createdBy: '',
  createdDate: '',
  updatedBy: '',
  updatedDate: '',
  code: '',
  name: '',
  date: '',
  details: '',
};

export const sampleInquiries = [
  {
    id: 'INQ-0001',
    requestedBy: 'Anna Reyes',
    requestDate: '2026-02-12',
    approvalStatus: 'Approved',
    responseBy: 'Mark Santos',
    responseDate: '2026-02-13',
    attention: 'Finance Team',
    preparedBy: 'Lea Cruz',
    notedBy: 'J. Mendoza',
    reference: 'REF-1032',
    createdBy: 'Anna Reyes',
    createdDate: '2026-02-12',
    updatedBy: 'Mark Santos',
    updatedDate: '2026-02-13',
    code: 'INQ-FIN-01',
    name: 'Payment Clarification',
    date: '2026-02-12',
    details: 'Requested clarification about payment term alignment for February billing.',
  },
];
