import {
  FiBarChart,
  FiBox,
  FiFileText,
  FiMessageSquare,
  FiUsers,
  FiSettings,
  FiArchive,
  FiPackage,
  FiLayers,
  FiTool,
  FiDatabase,
  FiList,
  FiGrid,
  FiUser,
  FiShoppingCart,
  FiTruck,
  FiFile,
  FiCreditCard,
  FiUserCheck,
  FiBriefcase,
  FiClipboard,
  FiDollarSign,
  FiFolder,
  FiUserPlus,
  FiInbox,
  FiSend,
  FiMap,
  FiAward,
  FiRepeat,
  FiSliders,
  FiPenTool,
  FiToggleLeft,
  FiAlignLeft,
  FiHardDrive,
  FiCpu,
  FiActivity,
  FiBookOpen,
  FiCheckSquare,
  FiDownload,
  FiUpload,
  FiPocket,
  FiTag,
  FiCompass,
  FiShare2,
} from 'react-icons/fi';

export const sidenavItems = [
  {
    label: 'Dashboard',
    icon: FiBarChart,
    href: '/dashboard',
    name: 'Dashboard',
  },
  {
    label: 'Customers',
    icon: FiUsers,
    href: '/customers',
    name: 'Customers',
  },
  {
    label: 'Suppliers',
    icon: FiUser,
    href: '/suppliers',
    name: 'Suppliers',
  },
  {
    label: 'Inquiry',
    icon: FiMessageSquare,
    href: '/inquiry',
    name: 'Inquiry',
  },
  {
    label: 'Projects',
    icon: FiLayers,
    name: 'Projects',
    children: [
      {
        label: 'Proposal',
        icon: FiSend,
        href: '/projects/proposal',
        name: 'Projects.Proposal',
      },
      {
        label: 'Projects',
        icon: FiBriefcase,
        href: '/projects/project',
        name: 'Projects.Projects',
      },
      // {
      //   label: 'Billings',
      //   icon: FiDollarSign,
      //   href: '/projects/billings',
      //   name: 'Projects.Billings',
      // },
      // {
      //   label: 'Collections',
      //   icon: FiFolder,
      //   href: '/projects/collections',
      //   name: 'Projects.Collections',
      // },
    ],
  },
  {
    label: 'Purchase',
    icon: FiShoppingCart,
    name: 'Purchase',
    children: [
      {
        label: 'Request',
        icon: FiInbox,
        href: '/purchase/requests',
        name: 'Purchase.Requests',
      },
      {
        label: 'Orders',
        icon: FiClipboard,
        href: '/purchase/orders',
        name: 'Purchase.Orders',
      },
    ],
  },
  {
    label: 'Finance',
    icon: FiCreditCard,
    name: 'Finance',
    children: [
      {
        label: 'Project Billings',
        icon: FiDollarSign,
        href: '/finance/billings',
        name: 'Finance.Billings',
      },
      // {
      //   label: 'Purchase Billing',
      //   icon: FiFile,
      //   href: '/finance/invoice',
      //   name: 'Finance.Invoices',
      // },
      {
        label: 'Collections',
        icon: FiFolder,
        href: '/finance/collections',
        name: 'Finance.Collections',
      },
      {
        label: 'Invoices',
        icon: FiFile,
        href: '/purchase/invoices',
        name: 'Purchase.Invoices',
      },
      {
        label: 'Payments',
        icon: FiPocket,
        href: '/purchase/payments',
        name: 'Purchase.Payments',
      },
    ],
  },
  // {
  //   label: 'Storage',
  //   icon: FiSettings,
  //   name: 'Storage',
  //   children: [
  //   ],
  // },
  {
    label: 'Materials',
    icon: FiPackage,
    name: 'Materials',
    children: [
      {
        label: 'Materials',
        icon: FiBox,
        href: '/materialsSettings/materials',
        name: 'Materials.Materials',
      },
      {
        label: 'Tools & Equipment',
        icon: FiTool,
        href: '/materialsSettings/tools',
        name: 'Materials.ToolsEquipment',
      },
      {
        label: 'Assembly',
        icon: FiShare2,
        href: '/materialsSettings/assembly',
        name: 'Materials.Assembly',
      },
    ],
  },
  {
    label: 'Inventory',
    icon: FiArchive,
    name: 'Inventory',
    children: [
      {
        label: 'Material Inventory',
        icon: FiGrid,
        href: '/inventory/material-inventory',
        name: 'Inventory.MaterialInventory',
      },
      {
        label: 'Tools Inventory',
        icon: FiHardDrive,
        href: '/inventory/tools-inventory',
        name: 'Inventory.ToolsInventory',
      },
      {
        label: 'Material Requests',
        icon: FiBookOpen,
        href: '/inventory/material-request',
        name: 'Inventory.MaterialRequests',
      },
      {
        label: 'Material Transfer',
        icon: FiRepeat,
        href: '/inventory/materialtransfer',
        name: 'Inventory.MaterialTransfer',
      },
      {
        label: 'Material Received',
        icon: FiDownload,
        href: '/inventory/materialreceived',
        name: 'Inventory.MaterialReceived',
      },
      {
        label: 'Inventory Movement',
        icon: FiActivity,
        href: '/inventory/inventory-movement',
        name: 'Inventory.InventoryMovement',
      },
      {
        label: 'Deliveries',
        icon: FiTruck,
        href: '/purchase/deliveries',
        name: 'Purchase.Deliveries',
      },
      {
        label: 'Inventory Report',
        icon: FiActivity,
        href: '/inventory/inventory-report',
        name: 'Inventory.Report',
      },
    ],
  },
  {
    label: 'Reports',
    icon: FiFileText,
    href: '/reports',
    name: 'Reports',
  },
  {
    label: 'Maintenance',
    icon: FiSliders,
    name: 'Maintenance',
    children: [
      {
        label: 'Warehouse',
        icon: FiDatabase,
        href: '/storagesettings/warehouse',
        name: 'Storage.Warehouse',
      },
      {
        label: 'Rack',
        icon: FiAlignLeft,
        href: '/storagesettings/rack',
        name: 'Storage.Rack',
      },
      {
        label: 'Staff',
        icon: FiUserCheck,
        href: '/staff',
        name: 'Staff',
      },
      {
        label: 'Users',
        icon: FiCompass,
        href: '/maintainance/users',
        name: 'Maintenance.Users',
      },
      {
        label: 'Roles',
        icon: FiUserPlus,
        href: '/maintainance/roles',
        name: 'Maintenance.Roles',
      },
      {
        label: 'Unit of Measure',
        icon: FiTag,
        href: '/maintainance/UOM',
        name: 'Maintenance.UOM',
      },
      {
        label: 'UOM Conversion',
        icon: FiToggleLeft,
        href: '/maintainance/UOMConvertion',
        name: 'Maintenance.UOMConversion',
      },
      // ...add more maintenance items here if needed
    ],
  },
];